version: '3.8'

services:
  flyway-migration-pistachio:
    image: flyway/flyway:latest
    container_name: flyway-migration-pistachio
    command: migrate
    volumes:
      - ./flyway/flyway.conf:/flyway/conf/flyway.conf
      - ./migrations:/flyway/sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h postgres -p 5432 -U shared_user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-network

networks:
  shared-network:
    external: true
